# Generated by Django 4.2.7 on 2024-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shippment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(blank=True, max_length=50, null=True)),
                ('SAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('SEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('SPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('RName', models.CharField(blank=True, max_length=50, null=True)),
                ('RAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('REmail', models.CharField(blank=True, max_length=50, null=True)),
                ('RPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('Origin', models.CharField(blank=True, max_length=50, null=True)),
                ('Destination', models.CharField(blank=True, max_length=50, null=True)),
                ('Mode', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('Weight', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=50, null=True)),
                ('PaymentMode', models.CharField(blank=True, max_length=50, null=True)),
                ('DepartureDate', models.CharField(blank=True, max_length=50, null=True)),
                ('PackageItems', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('datetimec', models.DateTimeField(auto_now_add=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
