# Generated by Django 4.2.7 on 2024-01-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippment',
            name='datetimecmain',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
