# Generated by Django 4.2.7 on 2024-01-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shippment_datetimecmain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='13c813853854', max_length=50, null=True),
        ),
    ]
