# Generated by Django 4.2.7 on 2024-01-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shippment_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='shippmenthistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippment',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='shippment',
            name='Remarks',
        ),
        migrations.RemoveField(
            model_name='shippment',
            name='Status',
        ),
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='ac9c78270002', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippment',
            name='history',
            field=models.ManyToManyField(blank=True, to='app.shippmenthistory'),
        ),
    ]
