# Generated by Django 4.2.7 on 2024-01-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shippmenthistory_remove_shippment_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippmenthistory',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='78d541cb5d5f', max_length=50, null=True),
        ),
    ]
