# Generated by Django 4.2.7 on 2024-01-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shippmenthistory_uuid_alter_shippment_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippment',
            old_name='Notes',
            new_name='Delivery',
        ),
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='70f7e41233e4', max_length=50, null=True),
        ),
    ]
