# Generated by Django 4.2.7 on 2024-01-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_notes_shippment_delivery_alter_shippment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='78b5b47c4188', max_length=50, null=True),
        ),
    ]
