# Generated by Django 4.2.7 on 2024-01-12 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_shippment_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippmenthistory',
            name='uuid',
        ),
        migrations.AddField(
            model_name='shippmenthistory',
            name='datetimec',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='9b37ebac982c', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippmenthistory',
            name='Status',
            field=models.CharField(blank=True, default=datetime.datetime(2024, 1, 12, 20, 37, 34, 331283), max_length=50, null=True),
        ),
    ]
