# Generated by Django 4.2.9 on 2024-01-13 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_shippmenthistory_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='e919a1a781f7', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippmenthistory',
            name='Status',
            field=models.CharField(blank=True, default=datetime.datetime(2024, 1, 13, 14, 17, 40, 869497), max_length=50, null=True),
        ),
    ]
