# Generated by Django 4.2.9 on 2024-02-25 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_shippment_raddress_alter_shippment_saddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='d329fbacf65b', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippmenthistory',
            name='Status',
            field=models.CharField(blank=True, default=datetime.datetime(2024, 2, 25, 10, 22, 55, 26977), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippmenthistory',
            name='datetimec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
