# Generated by Django 4.2.9 on 2024-02-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_shippment_uuid_alter_shippmenthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='5356fd59cbce', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippmenthistory',
            name='Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
