# Generated by Django 4.2.9 on 2024-02-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_shippment_uuid_alter_shippmenthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='7947eb3cc39d', max_length=50, null=True),
        ),
    ]
