# Generated by Django 4.2.9 on 2024-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_shippment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='bd391ae9f966', max_length=50, null=True),
        ),
    ]
