# Generated by Django 4.2.9 on 2024-02-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_shippment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='27d94f058765', max_length=50, null=True),
        ),
    ]
