# Generated by Django 4.2.9 on 2024-03-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_shippment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='PackageItems',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='3f30aac01dfc', max_length=50, null=True),
        ),
    ]
